(function(){
    var modules={
        "panel-main-spardac":    	        {url:"$H/m/panel-main.html",router:1},
        "dsst-form-spardac":                    {url:"$H/m/neurocog/dsst-form.html"},
        "finger-tapping6-after-form-spardac":   {url:"$H/m/neurocog/finger-tapping6-after-form.html",task_name:"Finger Tapping - Morning"},
        "finger-tapping-alt-form-spardac":      {url:"$H/m/neurocog/finger-tapping-alt-form.html"},
        "finger-tapping12-before-form-spardac": {url:"$H/m/neurocog/finger-tapping12-before-form.html",task_name:"Finger Tapping - Evening"},
        "finger-tapping12-alt-form-spardac":    {url:"$H/m/neurocog/finger-tapping12-alt-form.html"},
        "letter-cancellation-form-spardac":     {url:"$H/m/neurocog/letter-cancellation-form.html"},
        "nback1-form-spardac":                  {url:"$H/m/neurocog/nback1-form.html",task_name:"1-Back"},
        "nback2-form-spardac":                  {url:"$H/m/neurocog/nback2-form.html",task_name:"2-back"},
        "nback3-form-spardac":                  {url:"$H/m/neurocog/nback3-form.html",task_name:"3-Back"},
        "stroop-colour-form-spardac":           {url:"$H/m/neurocog/stroop-colour-form.html",},
        "stroop-text-form-spardac":             {url:"$H/m/neurocog/stroop-text-form.html"},
        "tower-london-form-spardac":            {url:"$H/m/neurocog/tower-london-form.html"},
        "iapsl-form-spardac":                   {url:"$H/m/iaps/iapsl-form.html",task_name:""},
        "iapsr1-form-spardac":                   {url:"$H/m/iaps/iapsr1-form.html",task_name:""},
        "iapsr2-form-spardac":                   {url:"$H/m/iaps/iapsr2-form.html",task_name:""},
        "iapsle-form-spardac":                   {url:"$H/m/iaps/iapsle-form.html",task_name:""},
        "iapsr1e-form-spardac":                   {url:"$H/m/iaps/iapsr1e-form.html",task_name:""},
        "iapsr2e-form-spardac":                   {url:"$H/m/iaps/iapsr2e-form.html",task_name:""},
        
        "gses-data-spardac":                    {url:"$H/m/library/gses-data.html",Table:"gses-spardac",form_module:"gses-form-spardac"},
        "gses-form-spardac":                    {url:"$H/m/library/gses-form.html",Table:"gses-spardac",task_name:"General Self-Efficacy Scale"},
        "hpq-data-spardac":                     {url:"$H/m/library/hpq-data.html",Table:"hpq-spardac",form_module:"hpq-form-spardac"},
        "hpq-form-spardac":                     {url:"$H/m/library/hpq-form.html",Table:"hpq-spardac",task_name:"Health and Work Performance Questionnaire (HPQ)"},
        "poms-data-spardac":                    {url:"$H/m/library/poms-data.html",Table:"poms-spardac",form_module:"poms-form-spardac"},
        "poms-form-spardac":                    {url:"$H/m/library/poms-form.html",Table:"poms-spardac",task_name:"Profile of Mood States Questionnaire (POMS)"},
        "kss-data-spardac":                     {url:"$H/m/library/kss-data.html",Table:"kss-spardac",form_module:"kss-form-spardac"},
        "kss-form-spardac":                     {url:"$H/m/library/kss-form.html",Table:"kss-spardac",task_name:"Karolinska Sleepiness Scale (KSS)"},
        "medical-history-short-data-spardac":   {url:"$H/m/library/medical-history-short-data.html",Table:"medical-history-short-spardac",form_module:"medical-history-short-form-spardac"},
        "medical-history-short-form-spardac":   {url:"$H/m/library/medical-history-short-form.html",Table:"medical-history-short-spardac",task_name:"Medical History Short"},
        "sleep-history-data-spardac":           {url:"$H/m/library/sleep-history-data.html",Table:"sleep-history-spardac",form_module:"sleep-history-form-spardac"},
        "sleep-history-form-spardac":           {url:"$H/m/library/sleep-history-form.html",Table:"sleep-history-spardac",task_name:"Sleep History"},
        "ffs-data-spardac":                     {url:"$H/m/library/ffs-data.html",Table:"ffs-spardac",form_module:"ffs-form-spardac"},
        "ffs-form-spardac":                     {url:"$H/m/library/ffs-form.html",Table:"ffs-spardac",task_name:"Flinders Fatigue Scale"},
        "actiwatch-data-spardac":               {url:"$H/m/library/actiwatch-data.html",Table:"actiwatch-spardac",form_module:"actiwatch-form-spardac"},
        "actiwatch-form-spardac":               {url:"$H/m/library/actiwatch-form.html",Table:"actiwatch-spardac"},
        "eq-5d-data-spardac":                   {url:"$H/m/library/eq-5d-data.html",Table:"eq-5d-spardac",form_module:"eq-5d-form-spardac"},
        "eq-5d-form-spardac":                   {url:"$H/m/library/eq-5d-form.html",Table:"eq-5d-spardac",task_name:"EQ-5D-5L instrument"},
        "sf36-data-spardac":                    {url:"$H/m/library/sf36-data.html",Table:"sf36-spardac",form_module:"sf36-form-spardac"},
        "sf36-form-spardac":                    {url:"$H/m/library/sf36-form.html",Table:"sf36-spardac",task_name:"Short Form Survey Instrument (SF36)"},
        "iwqlq-data-spardac":                   {url:"$H/m/library/iwqlq-data.html",Table:"iwqlq-spardac",form_module:"iwqlq-form-spardac"},
        "iwqlq-form-spardac":                   {url:"$H/m/library/iwqlq-form.html",Table:"iwqlq-spardac",task_name:"Impact of Weight on Quality of Life Questionnaire (IWQLQ)"},
        "brief-illness-perception-questionnaire-data-spardac":   {url:"$H/m/library/brief-illness-perception-questionnaire-data.html",Table:"brief-illness-perception-questionnaire-spardac",form_module:"brief-illness-perception-questionnaire-form-spardac"},
        "brief-illness-perception-questionnaire-form-spardac":   {url:"$H/m/library/brief-illness-perception-questionnaire-form.html",Table:"brief-illness-perception-questionnaire-spardac",task_name:"Brief Illness Perception Questionnaire"},
        "breif-sexual-function-inventory-data-spardac":   {url:"$H/m/library/breif-sexual-function-inventory-data.html",Table:"breif-sexual-function-inventory-spardac",form_module:"breif-sexual-function-inventory-form-spardac"},
        "breif-sexual-function-inventory-form-spardac":   {url:"$H/m/library/breif-sexual-function-inventory-form.html",Table:"breif-sexual-function-inventory-spardac",task_name:"Brief Sexual Function Inventory"},
        "female-sexual-function-index-data-spardac":   {url:"$H/m/library/female-sexual-function-index-data.html",Table:"female-sexual-function-index-spardac",form_module:"female-sexual-function-index-form-spardac"},
        "female-sexual-function-index-form-spardac":   {url:"$H/m/library/female-sexual-function-index-form.html",Table:"female-sexual-function-index-spardac",task_name:"Female Sexual Function Index (FSFI)"},
        "three-factor-eating-questionnaire-data-spardac":   {url:"$H/m/library/three-factor-eating-questionnaire-data.html",Table:"three-factor-eating-questionnaire-spardac",form_module:"three-factor-eating-questionnaire-form-spardac"},
        "three-factor-eating-questionnaire-form-spardac":   {url:"$H/m/library/three-factor-eating-questionnaire-form.html",Table:"three-factor-eating-questionnaire-spardac",task_name:"Three-Factor Eating Questionnaire (TFEQ-R18)"},
        "glasgow-content-of-thoughts-inventory-data-spardac":   {url:"$H/m/library/glasgow-content-of-thoughts-inventory-data.html",Table:"glasgow-content-of-thoughts-inventory-spardac",form_module:"glasgow-content-of-thoughts-inventory-form-spardac"},
        "glasgow-content-of-thoughts-inventory-form-spardac":   {url:"$H/m/library/glasgow-content-of-thoughts-inventory-form.html",Table:"glasgow-content-of-thoughts-inventory-spardac",task_name:"Glasgow Content of Thoughts Inventory"},
        "glasgow-sleep-effort-scale-data-spardac":   {url:"$H/m/library/glasgow-sleep-effort-scale-data.html",Table:"glasgow-sleep-effort-scale-spardac",form_module:"glasgow-sleep-effort-scale-form-spardac"},
        "glasgow-sleep-effort-scale-form-spardac":   {url:"$H/m/library/glasgow-sleep-effort-scale-form.html",Table:"glasgow-sleep-effort-scale-spardac",task_name:"Glasgow Sleep Effort Scale"},
        "pre-sleep-arousal-scale-data-spardac":   {url:"$H/m/library/pre-sleep-arousal-scale-data.html",Table:"pre-sleep-arousal-scale-spardac",form_module:"pre-sleep-arousal-scale-form-spardac"},
        "pre-sleep-arousal-scale-form-spardac":   {url:"$H/m/library/pre-sleep-arousal-scale-form.html",Table:"pre-sleep-arousal-scale-spardac",task_name:"Pre-Sleep Arousal Scale"},
        "stanford-sleepiness-scale-data-spardac":   {url:"$H/m/library/stanford-sleepiness-scale-data.html",Table:"stanford-sleepiness-scale-spardac",form_module:"stanford-sleepiness-scale-form-spardac"},
        "stanford-sleepiness-scale-form-spardac":   {url:"$H/m/library/stanford-sleepiness-scale-form.html",Table:"stanford-sleepiness-scale-spardac",task_name:"Stanford Sleepiness Scale"},
        "dbas-16-data-spardac":                 {url:"$H/m/library/dbas-16-data.html",Table:"dbas-16-spardac",form_module:"dbas-16-form-spardac"},
        "dbas-16-form-spardac":                 {url:"$H/m/library/dbas-16-form.html",Table:"dbas-16-spardac",task_name:"Dysfunctional Beliefs and Attitudes about Sleep (DBAS-16)"},
        "multidimensional-fatigue-symptom-inventory-data-spardac":   {url:"$H/m/library/multidimensional-fatigue-symptom-inventory-data.html",Table:"multidimensional-fatigue-symptom-inventory-spardac",form_module:"multidimensional-fatigue-symptom-inventory-form-spardac"},
        "multidimensional-fatigue-symptom-inventory-form-spardac":   {url:"$H/m/library/multidimensional-fatigue-symptom-inventory-form.html",Table:"multidimensional-fatigue-symptom-inventory-spardac",task_name:"Multidimensional Fatigue Symptom Inventory"},
        "fatigue-symptom-inventory-data-spardac":   {url:"$H/m/library/fatigue-symptom-inventory-data.html",Table:"fatigue-symptom-inventory-spardac",form_module:"fatigue-symptom-inventory-form-spardac"},
        "fatigue-symptom-inventory-form-spardac":   {url:"$H/m/library/fatigue-symptom-inventory-form.html",Table:"fatigue-symptom-inventory-spardac",task_name:"Fatigue Symptom Inventory"},
        "hads-data-spardac":                    {url:"$H/m/library/hads-data.html",Table:"hads-spardac",form_module:"hads-form-spardac"},
        "hads-form-spardac":                    {url:"$H/m/library/hads-form.html",Table:"hads-spardac",task_name:"Hospital Anxiety and Depression Scale (HADS)"},
        "pvt-data-spardac":                     {url:"$H/m/library/pvt-data.html",Table:"pvt-spardac",form_module:"pvt-form-spardac"},
        "pvt-form-spardac":                     {url:"$H/m/library/pvt-form.html",Table:"pvt-spardac"},
        "pvt-pc-data-spardac":                     {url:"$H/m/library/pvt-pc-data.html",Table:"pvt-pc-spardac",form_module:"pvt-pc-form-spardac"},
        "pvt-pc-form-spardac":                     {url:"$H/m/library/pvt-pc-form.html",Table:"pvt-pc-spardac"},
        "stop-bang-data-spardac":               {url:"$H/m/library/stop-bang-data.html",Table:"stop-bang-spardac",form_module:"stop-bang-form-spardac"},
        "stop-bang-form-spardac":               {url:"$H/m/library/stop-bang-form.html",Table:"stop-bang-spardac",task_name:"Stop-Bang"},
        "gds-data-spardac":                     {url:"$H/m/library/gds-data.html",Table:"gds-spardac",form_module:"gds-form-spardac"},
        "gds-form-spardac":                     {url:"$H/m/library/gds-form.html",Table:"gds-spardac",task_name:"Geriatric Depression Scale"},
        "ispq-data-spardac":                    {url:"$H/m/library/ispq-data.html",Table:"ispq-spardac",form_module:"ispq-form-spardac"},
        "ispq-form-spardac":                    {url:"$H/m/library/ispq-form.html",Table:"ispq-spardac",task_name:"Impact to Sleep and Preferences Questionnaire"},
        "tipi-data-spardac":                    {url:"$H/m/library/tipi-data.html",Table:"tipi-spardac",form_module:"tipi-form-spardac"},
        "tipi-form-spardac":                    {url:"$H/m/library/tipi-form.html",Table:"tipi-spardac",task_name:"Ten-Item Personality Inventory (TIPI)"},
        "pvt-cal-data-spardac":                    {url:"$H/m/library/pvt-cal-data.html",Table:"pvt-cal-spardac",form_module:"pvt-cal-form-spardac"},
        "pvt-cal-form-spardac":                    {url:"$H/m/library/pvt-cal-form.html",Table:"pvt-cal-spardac"},
        "psggrr-data-spardac":                    {url:"$H/m/library/psggrr-data.html",Table:"psggrr-spardac",form_module:"psggrr-form-spardac",task_name:"Grael Research PSG Report"},
        "psggrr-form-spardac":                    {url:"$H/m/library/psggrr-form.html",Table:"psggrr-spardac",task_name:"Grael Research PSG Report"},
        "psg300-data-spardac":                    {url:"$H/m/library/psg300-data.html",Table:"psg300-spardac",form_module:"psg300-form-spardac",task_name:"PSG 300 Report"},
        "psg300-form-spardac":                    {url:"$H/m/library/psg300-form.html",Table:"psg300-spardac",task_name:"PSG 300 Report"},
        "clintrial-data-spardac":                    {url:"$H/m/spardac/clintrial-data.html",Table:"clintrial-spardac",form_module:"clintrial-form-spardac",task_name:"eCRF with Monitor function"},
        "clintrial-form-spardac":                    {url:"$H/m/spardac/clintrial-form.html",Table:"clintrial-spardac",task_name:"eCRF with Monitor function"},
    }
    for(p in modules){
        $vm.module_list[p]=modules[p];
        $vm.module_list[p].url=$vm.module_list[p].url.replace('$H',$vm.hosting_path);
    }
})();
